#!/usr/bin/env bash
# Set IFS to colon since /etc/passwd uses colon as delimiter
IFS=':'
while read -r username password uid gid description home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $description"
done < /etc/passwd

